Minor fixes, refactoring
skyrim-multiplayer/skymp pull request #1014
Opened 2022-03-11 01:14 UTC by Darkwood9612

2022-03-11 01:32 UTC, Pospelove requested changes
Overall looks good!

2022-03-11 01:32 UTC, Pospelove commented on skymp5-server/cpp/papyrus_vm_lib/VarValue.cpp
> +     constexpr inline std::string_view EMPTY_STR = "";
EMPTY_STR => kEmptyString

2022-03-12 07:37 UTC, nic11 commented on unit/VarValueTest.cpp
> +  VarValue arr((uint8_t)VarValue::Type::ObjectArray);
C-style cast

2022-03-13 00:15 UTC, Pospelove commented
Я не могу понять что но что то серьёзное развалилось (

2022-04-03 21:09 UTC, Pospelove commented
Sorry :(
I wasn't able to determine the reason for failure. We will probably get back to this PR once we have better tooling to detect the reason. Closing for now :((

2022-04-03 21:09 UTC, closed without merging