Implement server-side packet for lockpicking a container/door #1106
skyrim-multiplayer/skymp pull request #1116
Opened 2022-04-26 12:28 UTC by Retr0Wawe

2022-05-01 21:02 UTC, nic11 requested changes

2022-05-01 21:02 UTC, nic11 commented on skymp5-server/cpp/server_guest_lib/MpChangeForms.h
> +  std::optional<int> lockLevel = 0;
Hmm, does it need to be attached to any form? And be public? And probably by default it should be `nullopt` instead of `0`?

2022-05-01 21:02 UTC, nic11 commented on skymp5-server/cpp/server_guest_lib/MpObjectReference.cpp
> +
Extra empty line

2022-05-01 21:02 UTC, nic11 commented on skymp5-server/cpp/server_guest_lib/PacketParser.cpp
> +        //�������� ������ � ���������� �� �������� ����
Some encoding problems. And it's better to leave comments in English

2023-03-02 12:48 UTC, Pospelove commented
closing due to inactivity. please let us know if you'll be available to get back to this

2023-03-02 12:48 UTC, closed without merging