fix: linux build
skyrim-multiplayer/skymp pull request #1290
Opened 2023-01-01 11:28 UTC by Korisss

Without this fix, I get a ChakraCore linking error (CMake can't find the ChakraCore library) and function not found error in ScriptStorage.cpp

2023-01-01 11:28 UTC, Korisss commented
![изображение](https://user-images.githubusercontent.com/72399290/210169161-c05589b5-24f7-430f-85bb-d9e1796da0b5.png)

2023-01-01 11:29 UTC, Korisss commented
![изображение](https://user-images.githubusercontent.com/72399290/210169178-1e8f4618-62db-4bab-9456-88424d17cdc0.png)
![изображение](https://user-images.githubusercontent.com/72399290/210169183-ae8fce0e-2ea5-4789-a0e1-ed261a66b071.png)

2023-01-01 16:12 UTC, Pospelove commented
@nic11

2023-01-03 23:39 UTC, Wedmer commented on skymp5-server/cpp/server_guest_lib/ScriptStorage.cpp
> +#include <cstring>
How this change relates to ChakraCore linking problem?

2023-01-03 23:42 UTC, Wedmer requested changes
Everything is ok except unrelated change in skymp5-server includes.

2023-01-04 18:41 UTC, Pospelove commented
https://github.com/skyrim-multiplayer/skymp/blob/main/docs/docs_maintainer_rules.md#commit-names

2023-01-05 15:50 UTC, nic11 commented
Thanks for the PR, it was upstreamed to vcpkg (https://github.com/microsoft/vcpkg/pull/28689) and will be applied with vcpkg update: #1295

Also, looks fine for my build now :+1: 
![Screenshot_20230105_162806](https://user-images.githubusercontent.com/11034375/210816861-bd3050b9-88b6-4fe9-944b-b9b292a7f960.png)

2023-01-05 15:50 UTC, closed without merging