feat(skymp5-server): implement an imitation of bound wepons
skyrim-multiplayer/skymp pull request #1294
Opened 2023-01-05 14:08 UTC by che6a

Closes #1279.

2023-03-01 17:03 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/PieScript.cpp
> +        .Then([bookBaseId, boundWeaponBaseId, &actor](Viet::Void) {
&actor can be destroyed at this point. so instead of & we should use formId and =

2023-03-02 19:12 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/PieScript.cpp
> +        .Then([bookBaseId, boundWeaponBaseId, &actor](Viet::Void) {
+ added items should be also equipped

2023-03-24 12:06 UTC, Wedmer approved these changes

2023-04-06 16:34 UTC, Pospelove requested changes

2023-04-06 16:34 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/MpObjectReference.h
> +  void ForceEquip(uint32_t baseId);
please remove this method and replace with sending a packet to a client to equip something

2023-04-06 16:34 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/SweetPieBoundWeapon.cpp
> +#include "SweetPieBoundWeapon.h"
do not add a separate file for this OR
at least name files the same way (for example Not SwwetPie*** and PieScript, but
SweetPie******* and SweetPieScript)

2023-04-13 12:18 UTC, Pospelove requested changes
please also do not change vcpkg version in this pr

2023-04-13 12:18 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/Inventory.cpp
> +void Inventory::SetWorn(uint32_t baseId, Worn worn)
this method isnt needed then

2023-04-13 12:35 UTC, che6a commented
Sure, I will fix this when I get back home.

2023-04-13 18:30 UTC, Pospelove requested changes
now vcpkg is deleted from the repo. it should stay the same

2023-04-13 18:50 UTC, Pospelove approved these changes

2023-04-13 18:50 UTC, che6a commented
@Pospelove ready fore review

2023-04-14 05:41 UTC, merged