optimized std::vector memory allocation
skyrim-multiplayer/skymp pull request #141
Opened 2021-08-19 19:41 UTC by bogdasar1985

2021-08-19 19:47 UTC, nic11 commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +    fl_size = File.tellg();
I think there's no reason to define it in the beginning, could say `const auto fileSize = ...` right here.

2021-08-19 19:47 UTC, nic11 commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +    arrayBytes.reserve(fl_size);  // Желательно, чтобы ближайшая степень двойки была, но с лимитом в 4096
1. Sounds more like a self-note, should not go to final commit.
2. No reason to round up to be power of two and/or divisible by 4096, allocators should do that by themselves. If only we care a lot about caching, but no reason to overoptimize stuff here, it requires a more global approach targeting entire project to have any effect.

P.S. Let's also keep all comments, including temporrary ones, in English

2021-08-22 15:28 UTC, nic11 approved these changes

2021-08-22 15:29 UTC, Pospelove commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +  storage.reserve(SizeStringTable);
This one also should be fixed even if this variable wasn't created by this PR. I think the more convenient name would be `stringTableSize`

2021-08-22 15:30 UTC, Pospelove commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +  temp.reserve(Size);
Please replace `Size` with `size`

2021-08-22 15:31 UTC, Pospelove commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +    fileSize = File.tellg();
Please replace `File` with `file`

2021-08-22 15:33 UTC, Pospelove requested changes

2021-08-22 15:33 UTC, Pospelove commented on skymp5-server/cpp/papyrus_vm_lib/Reader.cpp
> +  std::streampos fileSize;
Consider moving these definitions below to the place they are actually used

2021-08-22 18:43 UTC, Pospelove approved these changes

2021-08-22 18:44 UTC, merged