fix(skyrim-platform): improve event handlers safety
skyrim-multiplayer/skymp pull request #1496
Opened 2023-06-25 11:25 UTC by ZikkeyLS

2023-06-25 13:17 UTC, ZikkeyLS commented
@Pospelove

2023-06-25 13:26 UTC, Pospelove requested changes
may be I didn't see some similar cases with possible using null pointers.

please take a look carefully.

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto activeRefFormId = event->activeRef.get()->GetFormID();
event->activeRef.get() may be nullptr. needs check here

Use smth like event->subject ? event->subject->GetFormID() : 0;

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto refFormId = event->ref.get()->GetFormID();
same

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto actorFormId = event->actor.get()->GetFormID();
same

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto causeFormId = event->cause.get()->GetFormID();
same

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto objectId = event->object->GetFormID();
same

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto sellerId = event->seller->GetFormID();
same

2023-06-25 13:26 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +  auto markerType = event->mapMarkerData->type.get();
better to check mapMarkerData for nullptr too

2023-06-26 08:38 UTC, Pospelove requested changes
I forgot to ask you to add changelog line.

smth like "fixed events handling, should be less crashes"

2023-06-26 09:06 UTC, merged