fix(skyrim-platform): optimize texts collection
skyrim-multiplayer/skymp pull request #1515
Opened 2023-06-28 23:42 UTC by ZikkeyLS

close #1503

2023-06-29 00:57 UTC, ZikkeyLS commented
TO FIX: Currently crushes the game. (I guess because of new exceptions)

2023-06-29 08:59 UTC, ZikkeyLS commented
@Pospelove

2023-06-29 10:04 UTC, Pospelove requested changes
both set and get methods should throw on failure

2023-06-29 12:05 UTC, Pospelove requested changes

2023-06-29 12:05 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.cpp
> +  if (makeId->IsID(textId) == false) {
add exception here

2023-08-19 18:39 UTC, Pospelove approved these changes

2023-08-19 18:39 UTC, merged