feat(skyrim-platform): embedded cmd
skyrim-multiplayer/skymp pull request #1517
Opened 2023-06-30 18:56 UTC by VitaliyMubarakov

## Embedded console
Now you can enable cmd and get all the information from the game console in a separate window.

![image](https://github.com/skyrim-multiplayer/skymp/assets/58411554/103e0402-d807-4282-9175-40a09f81964b)

### New SkyrimPlatform.ini settings

- ```Cmd = false``` - This parameter controls whether the console is enabled.

- ```CmdOffsetLeft = 0``` - This parameter controls the console window offset from the left edge of the screen.

- ```CmdOffsetTop = 720``` - This parameter controls the console window offset from the top edge of the screen.

- ```CmdWidth = 1900``` - This parameter controls the width of the console window.

- ```CmdHeight = 317``` - This parameter controls the height of the console window.
> The default values are for full hd

### Why not just use a game console?

- Makes it easier to debug logs.
- If you close the console, the game closes with all background tasks.
- We get the ability to copy text.
- If you open the game in windowed mode, you can play and watch the console.

2023-06-30 18:57 UTC, VitaliyMubarakov commented
@Pospelove check

2023-06-30 19:06 UTC, VitaliyMubarakov commented
close https://github.com/skyrim-multiplayer/skymp/issues/1516

2023-07-01 07:00 UTC, Pospelove requested changes

2023-07-01 07:00 UTC, Pospelove commented on docs/release/dev/sp-embed-cmd.md
> +## Embedded console
could you please also create or update SP ini Settings docs?

2023-07-01 07:00 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.cpp
> +static WindowsConsolePrinter* windowsConsolePrinter = NULL;
theoretically, we should use smart pointers here (like sharedptr or unique_ptr)
WindowsConsolePrinter has destructor that calls FreeConsole
destructor for static var should be called on DLL unload (automatically).

so, could you please use unique_ptr/shared_ptr here, then check what happens if you close game (via menu, via qqq).

if all good, unique_ptr/shared_ptr would be better

Please also make vars g_ prefixed. our original code violates our own style guide. (global vars should look like g_globalVar)

2023-07-01 07:00 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.cpp
> +  if (windowsConsolePrinter)
please add {}

2023-07-01 07:00 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.h
> +void InitCMD(const int offsetLeft, const int offsetTop, const int width,
const int -> int. const bool ->bool. InitCMD -> InitCmd

2023-07-01 07:00 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/main.cpp
> +  if (!isCMD)
isCMD => isCmd
InitCMD => InitCmd
add {} to if

2023-07-01 08:48 UTC, VitaliyMubarakov commented on skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.cpp
> +  if (windowsConsolePrinter)
fix

2023-07-01 10:31 UTC, VitaliyMubarakov commented on skyrim-platform/src/platform_se/skyrim_platform/ConsoleApi.h
> +void InitCMD(const int offsetLeft, const int offsetTop, const int width,
fixed

2023-07-01 11:27 UTC, VitaliyMubarakov commented
@Pospelove ready

2023-07-03 11:03 UTC, Pospelove requested changes
1. please update https://github.com/skyrim-multiplayer/skymp/blob/0714e743c9bd16f97bf2c8d9222a112cce413e72/docs/docs_skyrim_platform.md
(add link to ini_settings.md)

2. sp_ini_settings -> ini_settings

Overall seems good. Nice job! Ansgar and our whole team loves it!

2023-07-04 20:26 UTC, Pospelove approved these changes

2023-07-04 20:27 UTC, merged

2023-07-04 20:27 UTC, Pospelove commented
awesome feature
thank u <3