feat(skyrim-platform): Add option to disable chromium
skyrim-multiplayer/skymp pull request #1657
Opened 2023-08-07 23:00 UTC by ZikkeyLS

closes #1595

2023-08-07 23:35 UTC, ZikkeyLS commented
@Pospelove

2023-08-08 10:25 UTC, Pospelove requested changes
please find where chromium initializes and add check for ChromiumEnabled

so people with ChromiumEnabled=false will not have Chromium eating their resources

2023-08-08 10:25 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatform.cpp
> +              BrowserApi::Register(e, browserApiState);
please move this check to functions of BrowserApi.

In case of chromium disabled throw an exception

2023-08-12 00:44 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/BrowserApi.h
> +  auto settings = Settings::GetPlatformSettings();
check here not needed

2023-08-20 13:35 UTC, ZikkeyLS commented
_Enabled_ and _Disabled_ comparison. (**there are 1 | 2 processes for DX11 left, linked with duplication of windows**)

**Enabled** (successfully load local server):
![Скриншот 20-08-2023 161855](https://github.com/skyrim-multiplayer/skymp/assets/68398139/6f0f1f8c-2e09-4438-bc05-5feab296b9b7)

**Disabled** (can't load server because of Chromium usage):
![Скриншот 20-08-2023 161943](https://github.com/skyrim-multiplayer/skymp/assets/68398139/8cabd81a-6ab7-4237-88f7-b6515e4aab2f)
![Скриншот 20-08-2023 162001](https://github.com/skyrim-multiplayer/skymp/assets/68398139/d382babc-5f02-4680-adce-65e67e4fd0e8)

2023-08-20 18:04 UTC, Pospelove requested changes
There should be no SkyrimPlatformCef processes

maybe you want to take a look at this code

https://github.com/skyrim-multiplayer/skymp/blob/74e30647c49b361d451073cad20400fd6ecab3c0/skyrim-platform/src/tilted/ui/MyChromiumApp.cpp#L95

2023-09-11 19:35 UTC, merged

2023-09-11 19:35 UTC, Pospelove commented
thank you !