fix(skymp5-server): decrease unarmed damage if the hit was blocked
skyrim-multiplayer/skymp pull request #1816
Opened 2024-01-17 20:37 UTC by che6a

@Pospelove, Aidmi asked me to add this. There's also a little improvement in readability, at least as I think.

2024-01-17 21:01 UTC, Pospelove requested changes
formula change is good

refactoring seems to be incorrect, let's revert as we don't have testing power for that

```c++
// changes value only if isShield is true
if (isShield) {
    isBlockingByShield = isShield;
}
```

```c++
// not equivalent, always changes value
isBlockingByShield = isShield;
```

2024-01-18 04:50 UTC, che6a commented
> ```c++
> // changes value only if isShield is true
> if (isShield) {
>     isBlockingByShield = isShield;
> }
> ```

Yep, that is the thing. `isBlockingByShield` is set to `false` by default and we change it to be `true` if and only if `isShield` is `true`, which means that, otherwise it will be `false`. Having that said, we get that if the `isShield` is true we're setting `isBlockingByShield` to `true` and if `isShield` is `false` we're not setting anything, leaving `isBlockingByShield` equal to `false` by default. So, not setting `isShield` when it's false and leaving `isBlockingByShield` with the default value and setting `isBlockingByShield` to `isShield` in case the latter is false are equivalent. (until this logic changes)

2024-01-18 09:30 UTC, Pospelove commented
ok let's do this

2024-01-18 18:36 UTC, Pospelove approved these changes

2024-01-18 18:36 UTC, merged