Add sync magic
skyrim-multiplayer/skymp pull request #2172
Opened 2024-09-30 08:13 UTC by Darkwood9612

2024-09-30 08:36 UTC, Pospelove requested changes
actionlistener.cpp: spdlog::info(fmt::format) -> spdlog::info

actionlistener.cpp: "SentToNeighbors" -> "RealFunctionName - " in logging

2024-09-30 08:36 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +    const bool isLeftHand =
changelog needed https://github.com/skyrim-multiplayer/skymp/tree/main/docs/release/dev

2024-09-30 08:43 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +    auto animVariables =
plz move anim vars out of the event

2024-10-09 13:39 UTC, Pospelove commented
TODO:
- Reverse-engineer and sync flames/bolts direction

2024-10-14 10:47 UTC, Pospelove commented on skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts
> +  Booleans: ArrayBuffer
Booleans => booleans
Floats => floats
Integers => integers

2024-10-15 08:32 UTC, Darkwood9612 commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +    auto animVariables =
done

2024-10-15 08:42 UTC, Darkwood9612 commented on skyrim-platform/src/platform_se/skyrim_platform/EventHandler.cpp
> +    const bool isLeftHand =
done

2024-10-15 08:42 UTC, Darkwood9612 commented on skyrim-platform/src/platform_se/codegen/convert-files/skyrimPlatform.ts
> +  Booleans: ArrayBuffer
done

2024-10-17 16:59 UTC, Pospelove commented
this is a good start. merging. we will resolve TODOs in follow ups

2024-10-17 17:00 UTC, merged