feat(skymp-client): use `startDeferredKill` to prevent unexpected death of other player characters
skyrim-multiplayer/skymp pull request #222
Opened 2021-09-19 14:52 UTC by ZikkeyLS

Closes #191

2021-09-19 19:01 UTC, alekcey0211 requested changes
1. Check msg.props twice
2. i think curly brackets must be on one line with if statement

2021-09-19 19:34 UTC, ZikkeyLS commented
That's basically test code, but I will fix and prettify it in next commits. Thanks for suggestions!

2021-09-20 20:54 UTC, Pospelove commented on skymp5-client/src/front/model.ts
> +  isMe?: boolean;
What is the purpose of this change?

2021-09-20 20:56 UTC, Pospelove commented on skymp5-client/src/front/remoteServer.ts
> +      this.worldModel.forms[i].isHostedByOther = msg.props.isHostedByOther as boolean;
What is the purpose of this change? Consider not making unrelated changes.

2021-09-20 20:57 UTC, Pospelove commented on skymp5-client/src/front/skympClient.ts
> +        this.updateData();
Please keep the original name. `updateData` is too common and doesn't say anything.

2021-09-20 20:58 UTC, Pospelove commented on skymp5-client/src/front/skympClient.ts
> +    deathSystem.usedRefID.filter((value) => targets.includes(value))
This line does not work as you expect. Filter doesn't modify the original array.  https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2021-09-20 21:00 UTC, Pospelove commented on skymp5-client/src/front/skympClient.ts
> +  private tryMakeActorImmortal(target : undefined)
Making actors immortal is not related to the inputs we send. Please write the code that is responsible for **correctly show other characters** in `view.ts`

2021-09-20 21:01 UTC, Pospelove commented
Two reviews are my mistake. The first set of comments is correct.

2021-09-20 21:34 UTC, Pospelove commented on skymp5-client/src/front/deathSystem.ts
> +export const MakeActorImmortal = (act: Actor): void => {
MakeActorImmortal  => makeActorImmortal

2021-09-21 09:38 UTC, alekcey0211 commented
I think you need to use `as` syntax in extreme cases. If TS show type error, you need to process it.

@Pospelove what do you think about this?

2021-09-21 20:50 UTC, alekcey0211 requested changes
1. MakeActorImmortal take Actor argument but why do you do the check ’act?’ Or you have the wrong type in the argument `act: Actor`
2. I prefer check like this 
```js
if (!player) {
  // some code
}
```
The code becomes more readable and in this case you add a check to ‘undefined’

Fix this and i approve it.

2021-09-21 21:18 UTC, ZikkeyLS commented
Hopefully all stuff is correct now

2021-09-22 05:14 UTC, alekcey0211 requested changes
Form the `if` statement correctly. Put a space after `if` and curly brackets
```js
if (condition) {
 // ...
}
```
and formatting arrow functions like this. 
```js
() => {
  // ...
}
```

2021-09-22 06:38 UTC, Pospelove approved these changes

2021-09-22 06:39 UTC, Pospelove requested changes
Oops, you better fix formatting as alekcey0211 says

2021-09-22 07:39 UTC, ZikkeyLS commented
Ready

2021-09-22 07:55 UTC, alekcey0211 commented
After `if` must be whitespace

2021-09-22 08:14 UTC, Pospelove requested changes
please `Right mouse button -> Format` in vs code

2021-09-22 08:16 UTC, ZikkeyLS commented
OK, I will fix all in home

2021-09-22 09:07 UTC, alekcey0211 commented
Or use combination `shift + alt + f` to format code

2021-09-22 14:02 UTC, ZikkeyLS commented
Format is ready!

2021-09-22 15:46 UTC, Pospelove approved these changes

2021-09-22 15:47 UTC, merged