closes #<202>
skyrim-multiplayer/skymp pull request #226
Opened 2021-09-21 04:34 UTC by d0gge

Closes #202 
Added percentages to `VisitProperties` for `MpActor`.

2021-09-21 11:58 UTC, Milord-Freeman requested changes

2021-09-21 11:58 UTC, Milord-Freeman commented on skymp5-server/cpp/server_guest_lib/GetBaseActorValues.h
> +
I'm not sure if this is the solution that was required - it might be reasonable to keep the value higher and only transform the data output.

2021-09-21 12:12 UTC, Milord-Freeman approved these changes

2021-09-22 06:29 UTC, Pospelove requested changes
Attribute percentages must be in change form.

2021-09-22 08:08 UTC, Pospelove approved these changes

2021-09-22 08:09 UTC, merged