feat(skymp5-server): send attribute percentage If crop attribute regeneration returned different percentage
skyrim-multiplayer/skymp pull request #257
Opened 2021-09-28 17:08 UTC by Dinakrab

closes #195

2021-09-28 17:26 UTC, alekcey0211 commented
Do you send percentage or values?

2021-09-28 17:31 UTC, Dinakrab commented
@alekcey0211 percentage

2021-09-28 18:30 UTC, Pospelove requested changes

2021-09-28 18:30 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/ActionListener.cpp
> +  if (health != healthPercentage || magicka != magickaPercentage ||
Please perform float comparison with epsilons: https://stackoverflow.com/questions/4915462/how-should-i-do-floating-point-comparison
(we should treat 0.5 as equal to 0.500001 for example)

2021-09-28 18:30 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/ActionListener.cpp
> +    actor->SendToUser(s.data(), s.size(), true);
Please unit test that the message is being delivered.

Here is an example on how to access messages sent during tests:
https://github.com/skyrim-multiplayer/skymp/blob/67bb639a2525e4bd193b9b704b86d430653a34c9/unit/PartOne_MovementTest.cpp#L30

2021-09-28 19:00 UTC, alekcey0211 commented
Is it correct to call health attributes when it’s actually healthPercentage? Will there be a misunderstanding?

2021-09-29 11:40 UTC, Pospelove commented
@alekcey0211 Unfortunately this PR just follows the structure of the ChangeValues packet that was already merged. I think we will change the structure in the future, but for this PR I wouldn't require to do it and I wouldn't require to keep two different versions of the ChangeValues packet.

2021-09-29 13:45 UTC, Pospelove approved these changes

2021-09-29 13:45 UTC, merged