feat(skymp5-server): reduce damage based on equipped armor
skyrim-multiplayer/skymp pull request #346
Opened 2021-10-14 23:05 UTC by nic11

Closes #337

2021-10-18 20:26 UTC, Pospelove commented
https://en.uesp.net/wiki/Oblivion:The_Complete_Damage_Formula

2021-10-31 16:58 UTC, Pospelove requested changes

2021-10-31 16:58 UTC, Pospelove commented on skymp5-server/cpp/lib_espm/espm.h
> +  // XXX: enum class?
Please remove the comment and convert `enum` to `enum class` then

2021-10-31 16:58 UTC, Pospelove commented on skymp5-server/cpp/lib_espm/espm.h
>      uint8_t animType = 0;
And here

2021-10-31 16:58 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/ActionListener.cpp
> +#include "formulas/IDamageFormula.h"
Both includes seem unused

2021-10-31 22:18 UTC, Pospelove commented on skymp5-server/cpp/CMakeLists.txt
> +file(GLOB_RECURSE src "${CMAKE_CURRENT_SOURCE_DIR}/server_guest_lib/**" "${CMAKE_SOURCE_DIR}/.clang-format")
no

2021-11-01 11:22 UTC, nic11 commented on skymp5-server/cpp/CMakeLists.txt
> +file(GLOB_RECURSE src "${CMAKE_CURRENT_SOURCE_DIR}/server_guest_lib/**" "${CMAKE_SOURCE_DIR}/.clang-format")
really no

2021-11-01 16:48 UTC, Pospelove requested changes
create TODO's on GitHub and we are good to go testing

2021-11-02 03:00 UTC, nic11 commented on unit/HitTest.cpp
> +  // XXX: test with other dummy formula? Test with actor with baseHealth > 100?
Oh and I've forgot about this btw

2021-11-02 20:05 UTC, Pospelove approved these changes

2021-11-02 20:09 UTC, merged