feat(skymp5-front): add chat widget
skyrim-multiplayer/skymp pull request #433
Opened 2021-10-24 16:09 UTC by q1000treadz

close #363

2021-11-05 11:48 UTC, JustCaptcha requested changes
Fix issues above and make rebase from the current main.

2021-11-05 11:48 UTC, JustCaptcha commented on skymp5-front/src/constructor.js
>      if (props.dynamicSize) {
Let's rewrite this part, please use switch for `props.elem.type`. we could extract long if conditions `(content_mainRef && content_mainRef.current && content_mainRef.current.clientHeight && content_mainRef.current.clientWidth)` to a separate constant.

2021-11-05 11:48 UTC, JustCaptcha commented on skymp5-front/src/components/SkyrimInput/index.js
> +                className={`skymp-input1`}
I don't like this approach. We should not use vague classNames. Please update SkyrimButton className to something else and leave SkyrimInput className as 'skymp-input'

2021-11-05 14:05 UTC, JustCaptcha requested changes

2021-11-05 14:05 UTC, JustCaptcha commented on skymp5-front/src/constructor.js
> +          if (content_mainRef && content_mainRef.current && content_mainRef.current.clientHeight && content_mainRef.current.clientWidth) {
you could extract:

```ts
if (content_mainRef && content_mainRef.current && content_mainRef.current.clientHeight && content_mainRef.current.clientWidth)
```

to

```ts
const isContentInitialized = content_mainRef && content_mainRef.current && content_mainRef.current.clientHeight && content_mainRef.current.clientWidth;
if (isContentInitialized) { ... }```

2021-11-05 14:05 UTC, JustCaptcha commented on skymp5-front/src/components/SkyrimInput/styles.scss
>    border: 3px solid rgba(157, 158, 158, 0.75);
You should update SkyrimButton className in `index.js` and `styles.scss` as well.

2021-11-05 14:36 UTC, JustCaptcha commented on skymp5-front/src/components/SkyrimInput/styles.scss
>    border: 3px solid rgba(157, 158, 158, 0.75);
Right now SkyrimInput and SkyrimButton have similar className - `skymp-input`

2021-11-05 23:52 UTC, JustCaptcha approved these changes

2021-11-06 01:18 UTC, Pospelove approved these changes

2021-11-06 01:18 UTC, merged