docs: improve events, hooks and other SP docs
skyrim-multiplayer/skymp pull request #446
Opened 2021-10-26 21:20 UTC by CarlosLeyvaAyala

I started working on expanding the documentation and I've documented `writeLogs()` .

I'm not **totally** convinced about what I've done with the new formatting (although I don't think it looks bad, either), especially with the format I used in new_methods.md, so I would like to hear a second opinion

2021-10-30 18:43 UTC, CarlosLeyvaAyala commented
Done for now.

I'll add more info when I learn more about SP and deal with standardizing format at another PR.

2021-10-30 22:22 UTC, Pospelove requested changes
Thanks! Some cosmetic changes requested, overall looks good

2021-10-30 22:22 UTC, Pospelove commented on docs/skyrim_platform/native.md
> +***WARNING***: Papyrus types and methods are only available inside [hooks][Hooks] or [new events][NewEvents] introduced by Skyrim Platform (except `tick`).
Honestly, I think they are available only in papyrus event hook. In anim event hook not. Let's check it.

2021-10-30 22:22 UTC, Pospelove commented on docs/skyrim_platform/new_events.md
> +  if (!armor || armor.getSlotMask() !== 0x4 || !b) return
missing semicolon here

2021-10-30 22:22 UTC, Pospelove commented on docs/skyrim_platform/new_events.md
> +  if(w)
Please fix formatting
```ts
if (w) {
  // ...
}
```

2021-10-30 22:22 UTC, Pospelove commented on docs/skyrim_platform/new_events.md
> +  if (event.actor.getFormID() !== Game.getPlayer()?.getFormID()) return
semicolon 2 :)

2021-10-30 22:22 UTC, Pospelove commented on docs/skyrim_platform/new_events.md
> +  if (fx?.getFormID() !== event.effect.getFormID()) return
and here

2021-11-03 10:13 UTC, Pospelove approved these changes

2021-11-05 12:34 UTC, merged