feat(skymp5-front): add Storybook
skyrim-multiplayer/skymp pull request #462
Opened 2021-11-02 02:09 UTC by JustCaptcha

Closes: [399](https://github.com/skyrim-multiplayer/skymp/issues/399)

2021-11-02 20:38 UTC, Pospelove commented on skymp5-front/src/components/FrameButton/index.tsx
> +    // name: string;
commented code

2021-11-02 20:39 UTC, Pospelove commented on skymp5-front/webpack.config.ts
> +      // {
and here

2021-11-20 11:32 UTC, nic11 commented
You commited `.DS_Store`

2021-11-20 13:53 UTC, Pospelove requested changes
Please fix json in skymp/unit:
```

: D:\a\skymp\skymp\unit\DistContentsTest.cpp(66): FAILED:
2: due to unexpected exception with message:
2:   Unexpected contents of 'D:/a/skymp/skymp/build/dist', see diff
2:   Excess files:
2:    + "server\\data\\ui\\00e4a2200c3e5ae71d67.ttf"
2:    + "server\\data\\ui\\268a0df3f0e2c23d1ea6.ttf"
2:    + "server\\data\\ui\\6f802bf60c545304b09e.ttf"
2:    + "server\\data\\ui\\855bfaf67c57745958d3.ttf"
2:    + "server\\data\\ui\\d213051bb6f28a25fb26.ttf"
2:    + "server\\data\\ui\\f4d6dc3e7665a2c2fc6d.png"
2:    + "server\\data\\ui\\fdf086661e1600f95a34.ttf"
2:   Missing files:
2:    - "server/data/ui/00e4a2200c3e5ae71d67e16d7990c68f.ttf"
2:    - "server/data/ui/268a0df3f0e2c23d1ea6e0e024316b34.ttf"
2:    - "server/data/ui/6f802bf60c545304b09e5fed8484f5c7.ttf"
2:    - "server/data/ui/855bfaf67c57745958d3a09367a4ccb8.ttf"
2:    - "server/data/ui/d213051bb6f28a25fb26372818032cf4.ttf"
2:    - "server/data/ui/fdf086661e1600f95a34561c377e0a9e.ttf"
```

Also remove DS_Store file

2021-11-22 01:26 UTC, Pospelove requested changes
oops we need to resolve conflicts again

2021-11-23 19:51 UTC, Pospelove approved these changes

2021-11-23 19:52 UTC, merged