Printing unhandled messages into the server console
skyrim-multiplayer/skymp pull request #465
Opened 2021-11-02 16:20 UTC by temMartik

2021-11-02 20:20 UTC, Pospelove requested changes
1) Please fix the formatting
2) print **unknown** messages. you currently print **known** messages. it's good, but out of the original task's scope.
3) use debug instead of info
4) remove skymp5-client changes

2021-11-03 14:28 UTC, Pospelove requested changes
```
spdlog::debug("Got uncknown message from {}", rawMsgData.userId);
```
Please also write **JSON contents** of unknown messages.
Please remove all other changes since they are out of the task's scope. They **will** be hard to review and fix.

2021-11-10 18:27 UTC, nic11 reviewed
Several comments more in addition.

And please remove skymp5-server.lnk and package-locks

2021-11-10 18:27 UTC, nic11 commented on skymp5-client/src/remoteServer.ts
> +
Meaningless change

2021-11-10 18:27 UTC, nic11 commented on skymp5-server/cpp/server_guest_lib/PacketParser.cpp
> +      actionListener.OnUnknown(rawMsgData, data_);
I think the whole object should be printed, not just data. (Probably with some generic validation and truncating so we won't spam console with huge messages with like 1K bytes or more)

2021-11-10 18:27 UTC, nic11 commented on skymp5-server/cpp/server_guest_lib/PacketParser.cpp
> +    case MsgType::PutItem: {
Why here?

2021-12-01 13:15 UTC, Pospelove commented
Closing in favor of https://github.com/skyrim-multiplayer/skymp/pull/585

2021-12-01 13:15 UTC, closed without merging