internal: update vcpkg version
skyrim-multiplayer/skymp pull request #523
Opened 2021-11-10 17:25 UTC by Milord-Freeman

Just updated submodule revision to fix https://githubmemory.com/repo/microsoft/vcpkg/issues/18791

2021-11-10 19:20 UTC, nic11 commented
@Pospelove Probably no sense to keep fork https://github.com/skyrim-multiplayer/vcpkg, maybe just change the URL in https://github.com/skyrim-multiplayer/skymp/blob/main/.gitmodules and remove the fork?

2021-11-10 19:36 UTC, Pospelove requested changes
@nic11 is right, let's use microsoft/vcpkg instead of skyrim-multiplayer/vcpkg

2021-11-11 09:22 UTC, Pospelove commented
Guys! Remove these files after fetching version with the new vcpkg submodule revision

```
build/CMakeCache
build/CMakeFiles
skymp5-server\cmake-js-fetch-build\CMakeFiles
skymp5-server\cmake-js-fetch-build\CMakeCache
```

2021-11-11 09:22 UTC, Pospelove approved these changes

2021-11-11 09:23 UTC, merged