feat(skyrim-platform): added function to disable `Ctrl + PrtScn` hotkey
skyrim-multiplayer/skymp pull request #526
Opened 2021-11-11 17:32 UTC by russo-2025

```This hotkey changes the game speed to be based on framerate rather than real time, which means the game runs normal speed at 30 FPS. Higher than that, the game runs too fast (2x speed at 60 FPS, 4x at 120, etc.) and lower than that, it runs slower. Since not everyone can maintain a constant 60 FPS (framedrops in Riften are common), this hotkey is not allowed.```

description from the website https://www.thegamer.com/skyrim-tricks-work-banned/

2021-11-11 19:44 UTC, Pospelove requested changes
Can we block only Ctrl+PrintScreen? not PrintScreen at all

2021-11-11 19:49 UTC, russo-2025 commented
> Can we block only Ctrl+PrintScreen? not PrintScreen at all

this function does not disable the `Printscreen' key

2021-11-11 20:15 UTC, Pospelove commented
Thanks, I'll doc and/or rename and merge

2021-11-12 19:43 UTC, Pospelove approved these changes

2021-11-12 19:51 UTC, Pospelove approved these changes

2021-11-12 20:02 UTC, merged