feat(skymp5-front): rewrite SkyrimInput to TS
skyrim-multiplayer/skymp pull request #533
Opened 2021-11-12 18:35 UTC by JustCaptcha

2021-11-14 15:26 UTC, Pospelove requested changes

2021-11-14 15:26 UTC, Pospelove commented on skymp5-front/src/interfaces/buttons.ts
> +    onInput?: (any?: any) => void;
there can be concrete type
`onInput?: (text: string) => void | () => void | (isChecked: boolean) => void`

2021-11-16 09:08 UTC, Pospelove requested changes

2021-11-16 09:08 UTC, Pospelove commented on skymp5-front/src/interfaces/buttons.ts
> +    onInput?: (any?: any) => void;
So there is still `any`

2021-11-20 11:33 UTC, nic11 commented
@JustCaptcha @Pospelove `refact`, I guess?

2021-11-20 11:43 UTC, vladdenisov commented
Will we use `onInput` on buttons? Or we will stay with `onClick`?

2021-11-20 13:58 UTC, Pospelove requested changes
The PR isn't buildable. Please check build errors in CI

2021-11-20 13:59 UTC, Pospelove commented
https://github.com/skyrim-multiplayer/skymp/runs/4272767380?check_suite_focus=true#step:13:462

2021-11-20 16:37 UTC, vladdenisov commented
> The PR isn't buildable. Please check build errors in CI

one of the reasons is that we used `onClick` property for buttons and it was changed here to `onInput`

2021-11-22 01:25 UTC, Pospelove approved these changes

2021-11-22 01:25 UTC, merged