Print unhandled messages
skyrim-multiplayer/skymp pull request #585
Opened 2021-12-01 01:51 UTC by artemmartyhin

2021-12-02 16:53 UTC, Pospelove requested changes

2021-12-02 16:53 UTC, Pospelove commented on skymp5-server/cpp/server_guest_lib/ActionListener.cpp
> +  spdlog::debug("Got unhandled message: {}", data);
data.get_c_str() intstead

2021-12-02 16:53 UTC, Pospelove commented on skymp5-client/src/remoteServer.ts
please remove ts changes

2021-12-08 10:48 UTC, Pospelove approved these changes

2021-12-08 11:03 UTC, Pospelove commented
oops approved by mistake

2021-12-08 11:04 UTC, Pospelove commented
@nic11 Use https://simdjson.org/api/0.3.1/classsimdjson_1_1minify.html
get_string seem to get string from string value instead of printing as json

2021-12-10 04:03 UTC, nic11 commented
Gotta test it somehow...

2021-12-10 08:56 UTC, Pospelove approved these changes

2021-12-10 08:59 UTC, Pospelove approved these changes

2021-12-12 18:59 UTC, merged