Add text render api for js
skyrim-multiplayer/skymp pull request #698
Opened 2021-12-25 19:38 UTC by Retr0Wawe

2021-12-25 19:56 UTC, Pospelove reviewed
1. Plz no commented code and no //Getters comment
2. We need to test if Cyrillic symbols work
3. We need some kind of texts limit. 1000 or 10000. some reasonable number

TODO: for me - think about threading

2021-12-28 17:40 UTC, Pospelove requested changes
Please also do the following:
1. Fix CI errors
2. Add file with feature desctiption here (https://github.com/skyrim-multiplayer/skymp/tree/main/docs/release/dev)
(your description goes to changelog)
3. Add `texts.md` here https://github.com/skyrim-multiplayer/skymp/tree/main/docs/skyrim_platform (see win32, browser for reference)

2021-12-28 17:40 UTC, Pospelove commented on skyrim-platform/src/platform_se/skyrim_platform/main.cpp
> +  try {
this try/catch doesn't seem useful. consider removing it. or explain what kind of exceptions does it catch

2021-12-28 20:06 UTC, nic11 commented on skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.h
> +  static TextsCollection& GetSinglton() noexcept;
typo:
```suggestion
  static TextsCollection& GetSingleton() noexcept;
```

2021-12-28 20:07 UTC, Retr0Wawe commented on skyrim-platform/src/platform_se/skyrim_platform/TextsCollection.h
> +  static TextsCollection& GetSinglton() noexcept;
thanks

2022-01-09 08:53 UTC, Pospelove requested changes
1) Add file with feature desctiption here (https://github.com/skyrim-multiplayer/skymp/tree/main/docs/release/dev)
(your description goes to changelog)
2) Add texts.md here https://github.com/skyrim-multiplayer/skymp/tree/main/docs/skyrim_platform (see win32, browser for reference)
3) Write TypeScript definitions for the new API here https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/codegen/convert-files/Definitions.txt

2022-01-11 16:09 UTC, Pospelove approved these changes

2022-01-11 16:10 UTC, merged