Update SweetPieGameModeListener.ts
skyrim-multiplayer/skymp pull request #891
Opened 2022-01-29 20:44 UTC by Dinakrab

closes #838

2022-01-30 12:10 UTC, Pospelove requested changes

2022-01-30 12:10 UTC, Pospelove commented on skymp5-functions-lib/index.ts
> +  pointsByName.set('default', startPoints[0] as LocationalData);
Please do NOT use `as` when you just want to silence the compiler. It results in having incorrect code compiled.
`as` is like `reinterpret_cast`. You just tell the compiler that everything ok but everything is not.

LocationalData and startPoints elements have different types. We need to convert carefully.

https://github.com/skyrim-multiplayer/skymp/blob/97864007140c21f12bca2df987da48adfdd384c7/skymp5-functions-lib/src/types/mp.d.ts#L90
https://github.com/skyrim-multiplayer/skymp/blob/c2f87b2547b6839308b8aa7dd8168d2bd4db7a3e/skymp5-server/ts/settings.ts#L14

2022-01-30 12:10 UTC, Pospelove commented on skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
> +    if (round && round.players?.size === 0) {
Condition is always false. If you are in the round there is at least 1 player in the round. it's you. right?

2022-01-30 12:10 UTC, Pospelove commented on skymp5-functions-lib/index.ts
> +  pointsByName.set('default', startPoints[0] as LocationalData);
@Dinakrab **I see it will be too hard to fix so let's forget about startPoints and just use hall**

2022-01-30 14:47 UTC, Pospelove submitted a review, later dismissed

2022-01-30 14:47 UTC, Pospelove commented on skymp5-functions-lib/src/logic/SweetPieGameModeListener.ts
> +    this.controller.setSpawnPoint(actorId, this.hallSpawnPointName);
Please just forceLeaveRound instead

2022-01-30 20:04 UTC, nic11 commented on skymp5-functions-lib/index.ts
> +if(startPoints && typeof startPoints === 'object' && Array.isArray(startPoints)){
This `if` got erased altogether?

2022-02-01 18:52 UTC, nic11 commented on skymp5-functions-lib/index.ts
> +const gameModeListener = createGameModeListener(playerController, maps, serverSettings["sweetPieMinimumPlayersToStart"]);
Probably changes here are not needed anymore, so let's revert them

2022-02-01 23:32 UTC, nic11 approved these changes
And also testing shows that it's working

2022-02-01 23:33 UTC, merged